version: "3"


services:
  covid_scraper:
    build: StatisticManager/
    restart: always
    volumes:
      - db_volume:/usr/src/app/StatisticManager
    environment:
      - TZ=Europe/Moscow
  web_service:
    build: WebService/
    restart: always
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - "covid_scraper"

volumes:
  db_volume: